postgres:
  user: admin
  password: ikarikar
  host: postgresql
  database: projects
  maxConnections: 20
  metricsPort: 8082

mongo:
  user: admin
  password: ikarikar
  host: mongodb
  database: projects
  maxConnections: 20
  metricsPort: 8081

elasticsearch:
  host: "elasticsearch:9200"
  metricsPort: 8083
  indexName: "projects"

test:
  minClients: 1
  maxClients: 240
  stageIntervalS: 5
  requestDelayMs: 250
