debug: true

postgres:
  user: admin
  password: password123
  host: postgresql
  database: testdb
  maxConnections: 20
  metricsPort: 8082

mongo:
  user: admin
  password: password123
  host: mongodb
  database: testdb
  maxConnections: 20
  metricsPort: 8081

elasticsearch:
  host: "elasticsearch:9200"
  metricsPort: 8083
  indexName: "productss"

test:
  minClients: 1
  maxClients: 400
  stageIntervalS: 5
  requestDelayMs: 250
